- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: setup

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: php


- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: compose

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: apache2

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: mysql

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: pgsql

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: composer

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: startingservices

#- hosts: all
#  become: true
#  become_user: root
#  gather_facts: false
#  tasks:
#    - include_role:
#        name: cert

