- name: update and upgrade the servers
  apt:
      update_cache: yes
      upgrade: yes

- name: install apache2
  tags: apache, apache2, ubuntu
  apt:
   name:
    - apache2
   state: latest

- name: Print hostname and date/time
  shell: |
    hostname=$(hostname)
    date=$(TZ='Africa/Lagos' date +"%Y-%m-%d %T %Z")
    printf "Welcome to %s\nToday's date and time in Lagos, Nigeria is: %s\n" "$hostname" "$date"
  register: result

- name: Create the index.html file
  copy:
    dest: /var/www/html/index.html
    content: |
      <html>
        <body>
          {{ result.stdout }}
        </body>
      </html>

