---
- name: Remove default apache page
  file: name=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: create apache vhosts for domain
  template: src=web.conf.j2 dest="/etc/apache2/sites-available/{{ vhost_name }}.conf"

- name: permission for laravel conf file
  shell: sudo chmod -R 777 /etc/apache2/sites-available/{{ vhost_name }}.conf

- name: Update a2ensite
  command: a2ensite {{ vhost_name }}

- name: Enable the Apache rewrite module
  command:  a2enmod rewrite

  notify:
    - restart apache2
